INSERT INTO TODO_DATAS(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
VALUES (10001,'MERİC','İSMAİL ABİİ',CURRENT_DATE(),FALSE);

INSERT INTO TODO_DATAS(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
VALUES (10002,'MERİC','HOOOP',CURRENT_DATE(),FALSE);

INSERT INTO TODO_DATAS(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
VALUES (10003,'MERİC','NABIYON',CURRENT_DATE(),FALSE);

INSERT INTO TODO_DATAS(ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
VALUES (10004,'MERİC','NEYİ NABIYOM',CURRENT_DATE(),FALSE);